pull_request_rules:
  - name: automatic merge of development PRs into test
    conditions:
      - base=test
      - status-success=continuous-integration/travis-ci/branch
    actions:
      merge:
        method: merge
