# start all external services for the metadatamanagement app
# mongo and elasticsearch will be available on its default ports
# docker-compose start
version: "3.1"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/mongodb/data
      - MONGO_LOG_DIR=/data/mongodb/logs
    volumes:
      - ./data/mongodb/db:/data/mongodb/db
      - ./data/mongodb/logs:/data/mongodb/logs
    command: mongod
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    # ensure group has rwx on this directory
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    # goto localhost:8081 for viewing mail sent via smtp
    ports:
      - "8081:80"
      - "1025:25"
  postgres:
      image: postgres:12.2
      container_name: postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: keycloak
    environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8082:8080"
    depends_on:
        - postgres
        - maildev
