# outputs.tf

# output the load balancers dns name which needs to be aliased by
# dev.metadata.fdz.dzhw.eu
# test.metadata.fdz.dzhw.eu
# www.metadata.fdz.dzhw.eu
# metadata.fdz.dzhw.eu
output "alb_hostname" {
  value = aws_alb.load_balancer.dns_name
}

# DKIM tokens generated by SES. 
# These tokens should be used to create CNAME records used to verify SES Easy DKIM.
output "dkim" {
  value = aws_ses_domain_dkim.dzhw.dkim_tokens
}
