package eu.dzhw.fdz.metadatamanagement.common.rest.errors;

import java.io.Serializable;

/**
 * DTO for field errors.
 * 
 * @deprecated This has been generated by jhipster and must not be used by our domain object
 *             validation.
 */
public class FieldErrorDto implements Serializable {

  private static final long serialVersionUID = 1L;

  private final String objectName;

  private final String field;

  private final String message;

  FieldErrorDto(String dto, String field, String message) {
    this.objectName = dto;
    this.field = field;
    this.message = message;
  }

  public String getObjectName() {
    return objectName;
  }

  public String getField() {
    return field;
  }

  public String getMessage() {
    return message;
  }

}
