package eu.dzhw.fdz.metadatamanagement.common.rest.filter;


import java.io.IOException;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang.StringUtils;

/**
 * This filter is used in production, to serve static resources generated by "grunt build".
 * <p/>
 * <p>
 * It is configured to serve resources from the "dist" directory, which is the Grunt destination
 * directory.
 * </p>
 */
public class StaticResourcesProductionFilter implements Filter {

  @Override
  public void init(FilterConfig filterConfig) throws ServletException {
    // Nothing to initialize
  }

  @Override
  public void destroy() {
    // Nothing to destroy
  }

  @Override
  public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
      throws IOException, ServletException {

    if (!(request instanceof HttpServletRequest)) {
      return;
    }

    HttpServletRequest httpRequest = (HttpServletRequest) request;
    String contextPath = httpRequest.getContextPath();
    String requestUri = httpRequest.getRequestURI();
    requestUri = StringUtils.substringAfter(requestUri, contextPath);
    if (StringUtils.equals("/", requestUri)) {
      requestUri = "/index.html";
    }
    String newUri = "/dist" + requestUri;
    request.getRequestDispatcher(newUri)
      .forward(request, response);
  }
}
